server:
  port: 8001

spring:
  application:
    name: eureka_server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8002/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000 #剔除服务的间隔
