spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order

mybatis:
  type-aliases-package: com.cagayake.pojo
  mapper-locations: classpath:mybatis/*.xml

server:
  port: 9001

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #使用IP地址进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #设置显示服务的名字
    lease-renewal-interval-in-seconds: 2 #发送心跳的间隔
    lease-expiration-duration-in-seconds: 10 #续约到期的时间  即在多少秒之内没有收到心跳
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka,http://${eureka.instance.hostname}:8002/eureka

