server:
  port: 8080
spring:
  application:
    name: zuul

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #使用IP地址进行注册
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka,http://${eureka.instance.hostname}:8002/eureka

zuul:
  routes:
    user: /user/**
    order: /order/**
